### ISSUE TITLE
[5pt] As a user I want a 'Forgot password' page where i can reset my password

### ISSUE THREAD

**Issue by po-trottier** [po-trottier/concordia-instaclone#10]
I want to see a landing page that lets me easily create an account or log in to my existing account.

All the redirect logic is already there, we just need a good looking UI.

**Risk:** Low (We already have it working, just need a nicer looking one)
**Priority:** Medium (Just UI but one that many people will see)

**Comment by sfratt** [comment]
Acceptance Test

https://github.com/po-trottier/concordia-instaclone/blob/5a77b17c3af5b441dead62947963e375156942c5/features/login.feature#L46-L51
