### ISSUE TITLE
[2pt] As a user, I want to be able to sign in with my Google and Facebook accounts

### ISSUE THREAD

**Issue by po-trottier** [po-trottier/concordia-instaclone#11]
Parent Issue:
#10 

I want to be able to use "Sign in with Google" and "Sign in with Facebook" buttons instead of having to use my email and password.

Should be 2 lines of code... If needed I'll change the Facebook App to "prod" so that we can use the feature.

**Comment by po-trottier** [comment]
Completed by @LerouxManar and @po-trottier

**Comment by sfratt** [comment]
Acceptance Test

https://github.com/po-trottier/concordia-instaclone/blob/5a77b17c3af5b441dead62947963e375156942c5/features/login.feature#L14-L27
