### ISSUE TITLE
[1pt] As a user, I want to be able to add a description to my posts

### ISSUE THREAD

**Issue by po-trottier** [po-trottier/concordia-instaclone#15]
I want to be able to add a description when I post a photo.

**Risk:** Low (We're basically just building over what we already have)
**Priority:** High (Kind of a core feature that's important to the experience)

**Comment by po-trottier** [comment]
Completed by @LerouxManar

**Comment by sfratt** [comment]
Acceptance Test

https://github.com/po-trottier/concordia-instaclone/blob/5a77b17c3af5b441dead62947963e375156942c5/features/post.feature#L6-L15
