### ISSUE TITLE
[8pt] As a user, I want to post a picture to my profile.

### ISSUE THREAD

**Issue by sfratt** [po-trottier/concordia-instaclone#4]
I want to be able to post a photo to my profile and for other people to be able to see it.

Stephen:
- Logic to Add a Photo to the Database as well as the form to do so

P-O:
- Firebase Functions to link Feed to Profile 
- Simple Feed

**Comment by po-trottier** [comment]
Completed by @po-trottier

**Comment by sfratt** [comment]
Acceptance Test

https://github.com/po-trottier/concordia-instaclone/blob/5a77b17c3af5b441dead62947963e375156942c5/features/post.feature#L6-L15
