### ISSUE TITLE
[3pt] As a user I want to be able to modify my profile

### ISSUE THREAD

**Issue by po-trottier** [po-trottier/concordia-instaclone#48]
- Edit Email, Password, DP, Bio, Website

**Comment by po-trottier** [comment]
Completed by @radley-carpio and @po-trottier

**Comment by sfratt** [comment]
Acceptance Test

https://github.com/po-trottier/concordia-instaclone/blob/5a77b17c3af5b441dead62947963e375156942c5/features/profile.feature#L16-L26
