### ISSUE TITLE
[3pt] As a user, I want to follow a different user.

### ISSUE THREAD

**Issue by sfratt** [po-trottier/concordia-instaclone#5]
I want to be able to follow one or more users and see their photos on my timeline

**Comment by po-trottier** [comment]
Completed by @MansiEdi59

**Comment by sfratt** [comment]
Acceptance Test

https://github.com/po-trottier/concordia-instaclone/blob/5a77b17c3af5b441dead62947963e375156942c5/features/profile.feature#L34-L40
