### ISSUE TITLE
[5pt] As a user I want to be able to see post details

### ISSUE THREAD

**Issue by po-trottier** [po-trottier/concordia-instaclone#52]
Parent Issue:
#4 

Add a page where we can open a post and see all the comments on said post.

The url should have to form:
`https://baseurl.com/posts/123456`
Where `123456 `is the Post ID in the database.

**Comment by po-trottier** [comment]
Completed by @MansiEdi59

**Comment by sfratt** [comment]
Acceptance Test

https://github.com/po-trottier/concordia-instaclone/blob/5a77b17c3af5b441dead62947963e375156942c5/features/post.feature#L16-L22
