### ISSUE TITLE
[5pt] As a user, I want to leave a comment on a picture & like posts.

### ISSUE THREAD

**Issue by sfratt** [po-trottier/concordia-instaclone#6]
I want to be able to comment on a photo and for other users to see my comment.

**Risk:** Low (We're basically just building over what we already have)
**Priority:** High (Core feature that's important to the experience)

**Comment by po-trottier** [comment]
Completed by @sfratt (local like-button logic) @hodanourbakhsh (parts of the comment logic) and @po-trottier  (server like + server comment)

**Comment by sfratt** [comment]
Acceptance Test

https://github.com/po-trottier/concordia-instaclone/blob/5a77b17c3af5b441dead62947963e375156942c5/features/post.feature#L23-L36
