### ISSUE TITLE
[2pt] As a user I want to be able to search a picture by hashtag

### ISSUE THREAD

**Issue by EdiMansi** [po-trottier/concordia-instaclone#7]
I want to be able to search for a hashtag and find all the posts that have this tag.

**Risk:** Medium (We're basically just building over what we already have with a little bit of unknown)
**Priority:** Medium (Extra on of the features so it's kind of important)

**Comment by po-trottier** [comment]
Not Implemented

**Comment by po-trottier** [comment]
Partly completed by @hodanourbakhsh (parsing of the tags on the client side)
