### ISSUE TITLE
[4pt] As a user I awnt to be able to craete a new account

### ISSUE THREAD

**Issue by po-trottier** [po-trottier/concordia-instaclone#83]
I awnt to be able to sign-up and create a new customizable account with my email or google or facebook.

**Comment by po-trottier** [comment]
Completed by @LerouxManar

**Comment by sfratt** [comment]
Acceptance Test

https://github.com/po-trottier/concordia-instaclone/blob/5a77b17c3af5b441dead62947963e375156942c5/features/profile.feature#L6-L15
