### ISSUE TITLE
[2pt] As a user, I want to be able to search for a user

### ISSUE THREAD

**Issue by po-trottier** [po-trottier/concordia-instaclone#9]
I want to be able to search for a user that I want to follow.

**Risk:** Low (We're basically just building over what we already have)
**Priority:** Low (Extra feature that's not too significant)

**Comment by po-trottier** [comment]
Completed by @po-trottier

**Comment by sfratt** [comment]
Acceptance Test

https://github.com/po-trottier/concordia-instaclone/blob/5a77b17c3af5b441dead62947963e375156942c5/features/profile.feature#L27-L33
